name: create a new release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          # 圧縮形式
          type: zip
          # 圧縮したファイル名
          filename: test.zip
          directory: temp
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            temp/test.zip
